# Generated by Django 2.2 on 2019-08-08 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clicker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clicker',
            options={},
        ),
    ]
